### ISSUE TITLE
这份页面是什么时候保存的？

### ISSUE THREAD

**Issue by tvas1000** [Womsxd/pandownload.com_Pages_Backup#3]
现在pandownload内捐助二维码和这份页面上保存的二维码收款人不一致，怀疑有人趁机更改原服务器相关信息，想请问下这份页面是何时的？

**Comment by Womsxd** [comment]
在被封之后可以重新连接后保存的

**Comment by Womsxd** [comment]
https://web.archive.org/web/20200331163057/http://pandownload.com/
这里是3月31号保存的WX二维码，和我这个保存的一致
https://web.archive.org/web/20190628171335/http://pandownload.com/donate.html
19年6月28号的WX二维码，目被封
https://web.archive.org/web/20190929115750/http://pandownload.com/donate.html
19年9月29号保存的二维码，和pd里面一致

**Comment by Womsxd** [comment]
第一条出错了。。。
https://web.archive.org/web/20200331163057/http://pandownload.com/
这里的二维码是直接访问新站点的二维码(因为是js，没有保存)

**Comment by Womsxd** [comment]
https://web.archive.org/web/20191111230740/http://pandownload.com/images/wechat.png
不过可以确定的是我现在保存的二维码19年11月12日就出现在pd的网站上了

**Comment by Womsxd** [comment]
目前可以确定支付宝的二维码是正常的

**Comment by TkzcM** [comment]
> 现在pandownload内捐助二维码和这份页面上保存的二维码收款人不一致，怀疑有人趁机更改原服务器相关信息，想请问下这份页面是何时的？

能否发一下你看到的篡改后的二维码？
正常的应该是
微信 *露 支付宝 *丽琴（郭丽琴）

**Comment by Vocare123** [comment]
> 目前可以确定支付宝的二维码是正常的

没错 支付宝的二维码正常！

**Comment by tvas1000** [comment]
> https://web.archive.org/web/20200331163057/http://pandownload.com/
> 这里是3月31号保存的WX二维码，和我这个保存的一致
> https://web.archive.org/web/20190628171335/http://pandownload.com/donate.html
> 19年6月28号的WX二维码，目被封
> https://web.archive.org/web/20190929115750/http://pandownload.com/donate.html
> 19年9月29号保存的二维码，和pd里面一致

好的，谢谢啦
